$(document).ready(function(){
    $("#jsSenha").click(function(){
        if($('#jsPassword').val()=="no inicio de tudo"){
            $("#jsFase1").hide()
            $("#jsFase2").show()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()

        } if($('#jsPassword').val()=="A"){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").show()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
        }
        if($('#jsPassword').val()=="Era a companheira de todos"){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").show()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()

        }if($('#jsPassword').val()=="sempre feliz"){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").show()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
        }if($('#jsPassword').val()=="alegre alegria"){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").show()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
        }if($('#jsPassword').val()=="mas tudo mudou hoje em dia"){
            document.title = "a seguir, (fase)x-1"
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").show()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
        }if($('#jsPassword').val()=="uma pena, o meu amor não mudou ainda"){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").show()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
        }if($('#jsPassword').val()=="sim, tudo isso é uma história de amor"){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").show()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
            
            colocaEspera();
            
        }if($('#jsPassword').val()=="não quero passar meu sofrimento adiante, quero acabar com ele"){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").show()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
        }if($('#jsPassword').val()=="em milhares de maneiras eu penso mas somente uma funciona"){
            document.title="sim, é o mesmo de antes"
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").show()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
        }if($('#jsPassword').val()=="e nada fara com que tudo volte ao normal"){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").show()
            $("#jsFase13").hide()
            $("#jsFase14").hide()
        }if($('#jsPassword').val()=="uma pena, tudo preto, tudo escuro, mas em fim, acabou."){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").show()
            $("#jsFase14").hide()
        }if($('#jsPassword').val()=="adeus amarga vida."){
            $("#jsFase1").hide()
            $("#jsFase2").hide()
            $("#jsFase3").hide()
            $("#jsFase4").hide()
            $("#jsFase5").hide()
            $("#jsFase6").hide()
            $("#jsFase7").hide()
            $("#jsFase8").hide()
            $("#jsFase9").hide()
            $("#jsFase10").hide()
            $("#jsFase11").hide()
            $("#jsFase12").hide()
            $("#jsFase13").hide()
            $("#jsFase14").show()
        }if($('#jsPassword').val()=="torre eiffel"){
            alert("sim, tudo isso é uma história de amor")
        }
    })
})


var mostraSenha = function () {
    $("#jsEspere").html("não quero passar meu sofrimento adiante, quero acabar com ele");
    setTimeout(colocaEspera, 5000);
};

var colocaEspera = function () {
    $("#jsEspere").html("espere");
    setTimeout(mostraSenha, 900000);
};
